/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface SwapperInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "AddLiquidity"
      | "ETHTok"
      | "USDCTok"
      | "approveETHTok"
      | "approveUSDCTok"
      | "getETHTokReserves"
      | "getUSDCTokReserves"
      | "liquidityProviders"
      | "removeLiquidity"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "AddLiquidity",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "ETHTok", values?: undefined): string;
  encodeFunctionData(functionFragment: "USDCTok", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "approveETHTok",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveUSDCTok",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getETHTokReserves",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUSDCTokReserves",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "liquidityProviders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquidity",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "AddLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ETHTok", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "USDCTok", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveETHTok",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveUSDCTok",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getETHTokReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUSDCTokReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidityProviders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidity",
    data: BytesLike
  ): Result;
}

export interface Swapper extends BaseContract {
  connect(runner?: ContractRunner | null): Swapper;
  waitForDeployment(): Promise<this>;

  interface: SwapperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  AddLiquidity: TypedContractMethod<
    [_USDCTokAmount: BigNumberish, _ETHTokAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  ETHTok: TypedContractMethod<[], [string], "view">;

  USDCTok: TypedContractMethod<[], [string], "view">;

  approveETHTok: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  approveUSDCTok: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getETHTokReserves: TypedContractMethod<[], [bigint], "view">;

  getUSDCTokReserves: TypedContractMethod<[], [bigint], "view">;

  liquidityProviders: TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { USDCTokReserve: bigint; ETHTokReserve: bigint }],
    "view"
  >;

  removeLiquidity: TypedContractMethod<
    [_USDCTokAmount: BigNumberish, _ETHTokAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "AddLiquidity"
  ): TypedContractMethod<
    [_USDCTokAmount: BigNumberish, _ETHTokAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ETHTok"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USDCTok"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approveETHTok"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approveUSDCTok"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getETHTokReserves"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUSDCTokReserves"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "liquidityProviders"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { USDCTokReserve: bigint; ETHTokReserve: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "removeLiquidity"
  ): TypedContractMethod<
    [_USDCTokAmount: BigNumberish, _ETHTokAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
