/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ISwapperInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "AddLiquidity"
      | "getETHTokReserves"
      | "getUSDCTokReserves"
      | "removeLiquidity"
      | "swapETHTokForUSDCTok"
      | "swapUSDCTokForETHTok"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "AddLiquidity",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getETHTokReserves",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUSDCTokReserves",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquidity",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapETHTokForUSDCTok",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapUSDCTokForETHTok",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "AddLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getETHTokReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUSDCTokReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapETHTokForUSDCTok",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapUSDCTokForETHTok",
    data: BytesLike
  ): Result;
}

export interface ISwapper extends BaseContract {
  connect(runner?: ContractRunner | null): ISwapper;
  waitForDeployment(): Promise<this>;

  interface: ISwapperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  AddLiquidity: TypedContractMethod<
    [_USDCTokAmount: BigNumberish, _ETHTokAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getETHTokReserves: TypedContractMethod<[], [bigint], "view">;

  getUSDCTokReserves: TypedContractMethod<[], [bigint], "view">;

  removeLiquidity: TypedContractMethod<
    [_USDCTokAmount: BigNumberish, _ETHTokAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  swapETHTokForUSDCTok: TypedContractMethod<
    [_ETHTokAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  swapUSDCTokForETHTok: TypedContractMethod<
    [_USDCTokAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "AddLiquidity"
  ): TypedContractMethod<
    [_USDCTokAmount: BigNumberish, _ETHTokAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getETHTokReserves"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUSDCTokReserves"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "removeLiquidity"
  ): TypedContractMethod<
    [_USDCTokAmount: BigNumberish, _ETHTokAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapETHTokForUSDCTok"
  ): TypedContractMethod<[_ETHTokAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "swapUSDCTokForETHTok"
  ): TypedContractMethod<[_USDCTokAmount: BigNumberish], [void], "nonpayable">;

  filters: {};
}
