/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ctfSol from "./ctf.sol";
export type { ctfSol };
import type * as ethTokSol from "./ethTok.sol";
export type { ethTokSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as mulitsigSol from "./mulitsig.sol";
export type { mulitsigSol };
import type * as multisigFactorySol from "./multisigFactory.sol";
export type { multisigFactorySol };
import type * as multisigWuraSol from "./multisigWura.sol";
export type { multisigWuraSol };
import type * as multisigMainSol from "./multisig_main.sol";
export type { multisigMainSol };
import type * as swapperSol from "./swapper.sol";
export type { swapperSol };
import type * as usdcTokSol from "./usdcTok.sol";
export type { usdcTokSol };
export type { Lock } from "./Lock";
